# Generated by Django 5.1.2 on 2025-03-26 17:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('user', 'habit_name')},
        ),
        migrations.AddField(
            model_name='habit',
            name='completions',
            field=models.JSONField(blank=True, default=dict, help_text="Dictionary of completion dates in format {'YYYY-MM-DD': true}"),
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the habit was first created'),
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_colour',
            field=models.CharField(default='NO_COL', help_text='Hex color code for the habit', max_length=7),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateField(blank=True, default=None, help_text='Most recent completion date', null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the habit was last modified'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='accountability_partner',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional partner for accountability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_description',
            field=models.TextField(blank=True, default='', help_text='Optional description of your habit', null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_frequency',
            field=models.IntegerField(default=1, help_text='Frequency in days (e.g., 1 for daily, 7 for weekly)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_name',
            field=models.CharField(default='New Habit', help_text='The name of your habit', max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='streak_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Current consecutive completion streak'),
        ),
        migrations.RemoveField(
            model_name='habit',
            name='habit_completed',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='habit_image',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='habit_start_date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='last_updated',
        ),
    ]
