# Generated by Django 5.1.2 on 2025-04-02 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_habit_options_alter_habit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_colour',
            field=models.CharField(blank=True, default='NO_COL', help_text='Optional hex color code for the habit', max_length=7),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_frequency',
            field=models.IntegerField(blank=True, default=1, help_text='Optional frequency in days (e.g., 1 for daily, 7 for weekly)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_name',
            field=models.CharField(help_text='The name of your habit', max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='streak_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Current consecutive completion streak'),
        ),
    ]
