# Generated by Django 5.1.2 on 2025-04-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_worktask_worknote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worknote',
            name='tasks',
        ),
        migrations.AddField(
            model_name='worktask',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.worknote'),
        ),
    ]
