# Generated by Django 5.1.2 on 2025-05-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_worknote_tasks_worktask_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='achievements',
        ),
    ]
