# Generated by Django 5.1.2 on 2025-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_worknote_tasks_worktask_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='achievements',
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='bio',
            field=models.TextField(blank=True, help_text="User's biography", max_length=500, null=True),
        ),
    ]
