# Generated by Django 5.1.2 on 2025-05-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_post_achievements'),
        ('core', '0006_remove_post_achievements_applicationuser_bio'),
    ]

    operations = [
    ]
